### ISSUE TITLE
Commit?

### ISSUE THREAD

**Issue by legoboy0215** [jojoe77777/Development#2]
Can I just be able to commit in this Slapper? I don't want multiple Pulls and I will NOT mess it up...

**Comment by jojoe77777** [comment]
If you can tell me how to let you.. o_O

**Comment by legoboy0215** [comment]
Create a group and add me :)
Create a group by tapping the '+' and select orgnization.

**Comment by legoboy0215** [comment]
BTW, is this good? https://github.com/LegoPlugins/SlapperKill
LegoPlugins is a org I randomly made lol.
SlapperKill will support all mobs.

**Comment by jojoe77777** [comment]
I'll check it out soon, my internet is playing up right now.

**Comment by legoboy0215** [comment]
OK!
